app:
  image:
    repository: docvishnu1/vprofileapp
    tag: latest
    pullPolicy: IfNotPresent

db:
  image:
    repository: docvishnu1/vprofiledb
    tag: latest
    pullPolicy: IfNotPresent

web:
  image:
    repository: docvishnu1/vprofileweb
    tag: latest
    pullPolicy: IfNotPresent
