app:
  image:
    repository: docvishnu1/vprofileapp
    tag: "24030664218"
    pullPolicy: IfNotPresent
db:
  image:
    repository: docvishnu1/vprofiledb
    tag: latest
    pullPolicy: IfNotPresent
web:
  image:
    repository: docvishnu1/vprofileweb
    tag: latest
    pullPolicy: IfNotPresent
