app:
  image:
    repository: docvishnu1/vprofileapp
    tag: "24559935325"
    pullPolicy: IfNotPresent
db:
  image:
    repository: docvishnu1/vprofiledb
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
web:
  image:
    repository: docvishnu1/vprofileweb
    tag: latest
    pullPolicy: IfNotPresent
